version: '3.7'
services:
  postgres:
    image: postgres:13.4
    container_name: postgresql-db
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sample_database
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgresql-db
    restart: always
